### ISSUE TITLE
Update RegulaDocumentReader to use latest OpenCV version

### ISSUE THREAD

**Issue by eggnima** [regulaforensics/RegulaDocumentReader-iOS#1]
Would it be possible to update DocumentReader to utilize OpenCV 3.1.0 which supports bitcode?

**Comment by ikliashchou** [comment]
https://github.com/regulaforensics/RegulaDocumentReader-iOS/releases/download/v1.9.0/opencv-2.4-bitcode.zip
You may use OpenCV 2.4 from here, that supports bitcode.
